### ISSUE TITLE
Crash : CTInboxActivity

### ISSUE THREAD

**Issue by prateekgupta22195** [CleverTap/clevertap-android-sdk#95] opened 2020-08-22 21:50 UTC
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.clevertap.android.sdk.CTInboxStyleConfig.getNavBarTitle()' on a null object reference
       at com.clevertap.android.sdk.CTInboxActivity.onCreate(CTInboxActivity.java:82)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by piyush-kukadiya** [comment] 2020-08-24 08:41
Thanks @prateekgupta22195  for reporting. We will look into this and notify you once this fix is released. Meanwhile can you please share the steps to reproduce?

**Comment by darshanclevertap** [comment] 2020-09-08 06:36
@prateekgupta22195 Can you help us with some more details here? Were you able to reproduce the issue? If yes, then please share the steps with us, if no, then please share with us what % of users or devices were affected by this crash from the Crashlytics dashboard. This will help us get to the bottom of this. Also please share with us which is the current version of the CleverTap SDK you are using.

**Comment by darshanclevertap** [comment] 2020-09-15 07:03
@prateekgupta22195 Can you please help us with the details? Or else I'm sorry but we will have to close the issue due to lack of information.

**Closed** 2020-09-25 10:30 UTC
Labels: waiting

**Comment by junaid1460** [comment] 2022-05-16 10:34
Happening in flutter (android)
```java
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.my.app/com.clevertap.android.sdk.inbox.CTInboxActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean l5.j.t()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```java
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean l5.j.t()' on a null object reference
       at com.clevertap.android.sdk.inbox.CTInboxActivity.onDestroy(CTInboxActivity.java:197)
       at android.app.Activity.performDestroy(Activity.java:7218)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
Brand:LGE
Model:Nexus 5X
Orientation: Portrait
RAM free: 1.37 GB
Disk free: 425.99 MB

Version:Android 8.1.0
Orientation: Portrait
Rooted:No
```

```
logs:

1. Screen view
Parameters
  firebase_screen_class: CTInboxActivity

2. Screen view
Parameters
  firebase_screen_class: WebViewActivity
```
