### ISSUE TITLE
NullPointerException on CleverTapPlugin - Probably in notification flow

### ISSUE THREAD

**Issue by danilopena** [CleverTap/clevertap-android-sdk#98] opened 2020-09-01 11:51 UTC
Our firebase Crashlytics is registering this crash. We upgraded CleverTap, but the error persists.

Somebody can help?

Our version: 

In flutter: clevertap_plugin: 1.1.4
Android: implementation 'com.clevertap.android:clevertap-android-sdk:3.8.2'

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at com.clevertap.clevertap_plugin.CleverTapPlugin.runOnMainThread(CleverTapPlugin.java:1524)
       at com.clevertap.clevertap_plugin.CleverTapPlugin.invokeMethodOnUiThread(CleverTapPlugin.java:1540)
       at com.clevertap.clevertap_plugin.CleverTapPlugin.beforeShow(CleverTapPlugin.java:1566)
       at com.clevertap.android.sdk.CleverTapAPI.displayNotification(CleverTapAPI.java:4070)
       at com.clevertap.android.sdk.CleverTapAPI.notificationReady(CleverTapAPI.java:4028)
       at com.clevertap.android.sdk.CleverTapAPI$29.run(CleverTapAPI.java:4017)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by darshanclevertap** [comment] 2020-09-01 13:53
@danilopena Were you able to reproduce this issue? Or it is only being reported by Firebase Crashlytics? Also, can you share the devices and % of the user base affected?

**Comment by danilopena** [comment] 2020-09-01 14:05
@darshanclevertap only being reported by Firebase. I bring some prints to help with datas.

This data is from the last 3 days.

<img width="969" alt="Captura de Tela 2020-09-01 às 11 01 33" src="https://user-images.githubusercontent.com/6910678/91861003-b365a080-ec42-11ea-9224-0469ef3c905a.png">

<img width="484" alt="Captura de Tela 2020-09-01 às 11 01 53" src="https://user-images.githubusercontent.com/6910678/91861011-b52f6400-ec42-11ea-9bff-17e4feecf5d6.png">

<img width="484" alt="Captura de Tela 2020-09-01 às 11 02 04" src="https://user-images.githubusercontent.com/6910678/91861016-b5c7fa80-ec42-11ea-8a7f-2dc0c6edc03c.png">

<img width="481" alt="Captura de Tela 2020-09-01 às 11 02 19" src="https://user-images.githubusercontent.com/6910678/91861017-b6609100-ec42-11ea-884d-d3193390c42d.png">

91% of crashes are happening when the app is in the background. (last print)

**Comment by darshanclevertap** [comment] 2020-09-02 04:24
@danilopena Thank you for sharing the details. This crash is happening because of the CleverTap Flutter SDK and not because of the CleverTap Android SDK. We will fix this in the next version of the CleverTap Flutter SDK. Just for proper logistics can you reopen this on our [clevertap-flutter issues](https://github.com/CleverTap/clevertap-flutter/issues/new) page? 
I am closing this here so that we can track it in the right forum.

**Closed** 2020-09-02 04:24 UTC
Labels: flutter
