### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundIntentService"

### ISSUE THREAD

**Issue by pratyesh** [CleverTap/clevertap-android-sdk#120] opened 2020-11-19 17:56 UTC
Currently using sdk "**com.clevertap.android:clevertap-android-sdk:4.0.0**" .

**//our project sdk setup :-**
compileSdkVersion = 30
minSdkVersion = 19
targetSdkVersion = 30

**java.lang.RuntimeException: Unable to instantiate service com.clevertap.android.sdk.CTBackgroundIntentService:** **java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundIntentService"** on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-1.apk", zip file "/data/app/com.localqueen-1.apk", zip file "/data/data/com.localqueen/code_cache/secondary-dexes/com.localqueen-1.apk.classes2.zip", zip file "/data/data/com.localqueen/code_cache/secondary-dexes/com.localqueen-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/androidx.test.tools.crawler-1, /data/app-lib/com.localqueen-1, /vendor/lib, /system/lib, /lib]]
     FATAL EXCEPTION: main
Process: com.localqueen, PID: 7787
**java.lang.RuntimeException: Unable to instantiate service com.clevertap.android.sdk.CTBackgroundIntentService:** **java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundIntentService"** on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-1.apk", zip file "/data/app/com.localqueen-1.apk", zip file "/data/data/com.localqueen/code_cache/secondary-dexes/com.localqueen-1.apk.classes2.zip", zip file "/data/data/com.localqueen/code_cache/secondary-dexes/com.localqueen-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/androidx.test.tools.crawler-1, /data/app-lib/com.localqueen-1, /vendor/lib, /system/lib, /lib]]
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2792)
	at android.app.ActivityThread.access$1900(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1387)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5598)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundIntentService" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-1.apk", zip file "/data/app/com.localqueen-1.apk", zip file "/data/data/com.localqueen/code_cache/secondary-dexes/com.localqueen-1.apk.classes2.zip", zip file "/data/data/com.localqueen/code_cache/secondary-dexes/com.localqueen-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/androidx.test.tools.crawler-1, /data/app-lib/com.localqueen-1, /vendor/lib, /system/lib, /lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2789)
	... 10 more

**Comment by darshanclevertap** [comment] 2020-11-20 05:01
@pratyesh Did you check this https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md#-push-amplification-changes ?

**Comment by piyush-kukadiya** [comment] 2020-11-23 13:00
Duplicate of #115

**Closed** 2020-11-23 13:01 UTC
Labels: duplicate
