### ISSUE TITLE
Caused by java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService

### ISSUE THREAD

**Issue by sayagodshala** [CleverTap/clevertap-android-sdk#121] opened 2020-11-23 12:55 UTC
Caused by java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/com.vlv.aravali-S6cGxDiLOmMsfwabh4zD4Q==/base.apk", zip file "/data/app/com.vlv.aravali-S6cGxDiLOmMsfwabh4zD4Q==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.vlv.aravali-S6cGxDiLOmMsfwabh4zD4Q==/lib/arm64, /data/app/com.vlv.aravali-S6cGxDiLOmMsfwabh4zD4Q==/base.apk!/lib/arm64-v8a, /data/app/com.vlv.aravali-S6cGxDiLOmMsfwabh4zD4Q==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
       at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3936)
       at android.app.ActivityThread.access$1500(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by piyush-kukadiya** [comment] 2020-11-23 12:59
Duplicate of #115

**Closed** 2020-11-23 13:01 UTC
Labels: duplicate
