### ISSUE TITLE
Crash on App launch

### ISSUE THREAD

**Issue by nagraj-ec** [CleverTap/clevertap-android-sdk#117] opened 2020-10-29 13:49 UTC
Reported only with CT SDK Version 4.0.0

```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.clevertap.android.sdk.CTBackgroundJobService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/base.apk", zip file "/data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/split_config.arm64_v8a.apk", zip file "/data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/lib/arm64, /data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/base.apk!/lib/arm64-v8a, /data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.linkdokter.halodoc.android-Jmwm_boGeg8nWp_mPOlsAw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3940)
       at android.app.ActivityThread.access$1500(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by piyush-kukadiya** [comment] 2020-10-29 14:03
@nagraj-ec duplicate of #115

**Closed** 2020-10-30 08:02 UTC
Labels: duplicate
