### ISSUE TITLE
App Inbox not working in Android Fragment

### ISSUE THREAD

**Issue by ndmunoz10** [CleverTap/clevertap-android-sdk#42] opened 2019-12-06 16:34 UTC
Hello,

I'm trying to implement App Inbox from CleverTap in our Android app but it's not working.

I created the campaign through the CleverTap Dashboard with some tags/tabs, however inside the app when clicking on my custom view, the app inbox shows but no info is displayed. It only says "No Message(s) to show".

This is the code:

class MyFragment: CTInboxListener {
private var cleverTapDefaultInstance: CleverTapAPI? = null

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        cleverTapDefaultInstance = CleverTapAPI.getDefaultInstance(context)
        cleverTapDefaultInstance?.ctNotificationInboxListener = this
        cleverTapDefaultInstance?.initializeInbox()
    }

/**
     * Shows the CleverTap App Inbox activity with a custom predefined style
     */
    private fun displayCleverTapWithCustomStyle() {
        val context = context
        if (context != null) {
            val tabs: ArrayList<String> = ArrayList()
            tabs.add(ApplicationConstants.WHATS_NEW_TAB)
            tabs.add(ApplicationConstants.PROMOTIONS_TAB)
            val styleConfig = CTInboxStyleConfig()
            styleConfig.tabs = tabs
            // We perform and operation to remove any transparency in the color.
            styleConfig.tabBackgroundColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.topaz) and 0x00ffffff)
            styleConfig.selectedTabIndicatorColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.white) and 0x00ffffff)
            styleConfig.selectedTabColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.colorPrimary) and 0x00ffffff)
            styleConfig.unselectedTabColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.black) and 0x00ffffff)
            styleConfig.backButtonColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.white) and 0x00ffffff)
            styleConfig.navBarTitleColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.white) and 0x00ffffff)
            styleConfig.navBarTitle = getString(R.string.week_news)
            styleConfig.navBarColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.topaz) and 0x00ffffff)
            styleConfig.inboxBackgroundColor = "#" + Integer.toHexString(ContextCompat.getColor(context, R.color.white) and 0x00ffffff)
            cleverTapDefaultInstance?.showAppInbox(styleConfig)
        }
    }

override fun inboxDidInitialize() {
        Log.d("CLEVER TAP", "inbox did initialize")
    }

    override fun inboxMessagesDidUpdate() {
        Log.d("CLEVER TAP", "inbox did update")
        handleNotificationCounter()
    }
}

And I also saw this during debug:
Please upgrade com.android.support:design library to v28.0.0 to enable Tabs for App Inbox, dropping Tabs
2019-12-06 16:17:22.896 27040-27040/com.muy.app.staging D/CleverTap: Displaying Notification Inbox

So using tabs would not work if I'm using AndroidX? My clever tap sdk version is 3.6.1
Any help would be appreciated.

**Comment by darshanclevertap** [comment] 2019-12-07 13:06
@ndmunoz10 For the debug log and since you've migrated to AndroidX, I'd like to suggest adding the following dependencies - 

```
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.legacy:legacy-support-core-utils:1.0.0'

```    

As for you not receiving the Inbox messages, once you run the campaign via our dashboard, we take a few minutes to warm up the profiles which will eventually receive the messages. If you launch the app during that time, your profile will not receive the Inbox message. We are working on this from our back end. But I'd like you to create a new campaign, wait for a few minutes and see whether the inbox message reaches you. Let me know if this helps!

**Comment by ndmunoz10** [comment] 2019-12-07 14:23
Okay, I'll try waiting a bit more when I create campaigns.

As for the AndroidX issue, I added the two dependencies you included and the logs just says the same:
Please upgrade com.android.support:design library to v28.0.0 to enable Tabs for App Inbox, dropping Tabs 
:(

**Comment by darshanclevertap** [comment] 2019-12-07 15:05
Have you migrated completely to AndroidX or are you using Jetifier?

**Comment by ndmunoz10** [comment] 2019-12-07 15:12
Yes I'm using Jetifier

**Comment by ndmunoz10** [comment] 2019-12-12 14:37
Any news on this?

**Comment by kumaratulismu** [comment] 2019-12-16 16:42
@ndmunoz10  We are not able to reproduce this at our end and its working fine for fragment as well.

We need some your support in getting some more insight to debug it further. 

Can you help us with a sample app replicating the scenario. It would be useful in understanding the overall configuration you are using in your project.

**Comment by ndmunoz10** [comment] 2019-12-16 16:47
Actually my team and I had a call on Skype with some people from Clever Tap support, we mirrored our screen and showed them step by step our code. The told us that they didn't know why it wasn't working and that maybe it was because we are using Kotlin instead of Java (I don't think that is the problem). So I think we will have to use this without tabs until you upgrade to AndroidX

**Comment by kumaratulismu** [comment] 2020-03-05 05:59
Will be taken up with AndroidX support in the SDK. Closing as of now

**Closed by kumaratulismu** 2020-03-05 05:59 UTC
