### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException at `CleverTapAPI#showInApp` v3.4.2

### ISSUE THREAD

**Issue by wisnukurniawan** [CleverTap/clevertap-android-sdk#69] opened 2020-04-27 05:19 UTC
Hi Clevertap team, we got crash with error stack trace from crash reporting

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.add(ArrayList.java:468)
       at com.clevertap.android.sdk.CleverTapAPI.showInApp(CleverTapAPI.java:2648)
       at com.clevertap.android.sdk.CleverTapAPI.access$3500(CleverTapAPI.java:83)
       at com.clevertap.android.sdk.CleverTapAPI$20.run(CleverTapAPI.java:2633)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

This issue happen on android device 7, 8, 9 and device states 95% in background. We are using Clevertap SDK version 3.4.2. Is this issue already fixed in latest version? if yes we will update the version, if not please help to fix it since the issue make the app crashing. Thanks.

**Comment by wisnukurniawan** [comment] 2020-05-03 13:45
closed for now

**Comment by wisnukurniawan** [comment] 2020-05-05 02:03
The issue still happen even use latest version

**Comment by piyush-kukadiya** [comment] 2020-05-05 06:54
@wisnukurniawan We are looking into it. In mean time can you also please let us know if is it reproducible from your end? that will help us to solve issue at the earliest.

**Comment by wisnukurniawan** [comment] 2020-05-05 08:04
Unfortunately, we are not able to reproduce this issue.

**Comment by piyush-kukadiya** [comment] 2020-05-08 08:59
@wisnukurniawan We are unable to reproduce this issue at our end. We will fix it as soon as other users find similar issue and somehow we get to know steps for reproducing it. Closing this issue for now.

**Closed by piyush-kukadiya** 2020-05-08 08:59 UTC
